// lib/frameworks/svelte/useEngineCore.svelte
<script lang="ts">
    import { onMount, onDestroy } from "svelte"
    import { EngineCore } from "../../index";
    import type { IOptionsEngineCore } from "../../types";

    let app: EngineCore | null = null

    export let options: Partial<IOptionsEngineCore> = {}

    onMount(() => {
        app = new EngineCore(options)
    })

    onDestroy(() => {
        app = null
    })
</script>

// lib/frameworks/react/useEngineCore.ts
import { useEffect, useState } from "react";
import { EngineCore } from "../../index";
import type { IOptionsEngineCore } from "../../app/types";

export const useEngineCore = (options?: Partial<IOptionsEngineCore>) => {
    const [app, setApp] = useState<EngineCore | null>(null);

    useEffect(() => {
        const engine = new EngineCore(options);

        setApp(engine);

        return () => {
            setApp(null);
        };
    }, [options]);

    return app;
};
