// lib/frameworks/angular/useEngineCore.ts
import { Injectable, OnDestroy } from "@angular/core";
import { EngineCore } from "../../index";
import type { IOptionsEngineCore } from "../../app/types";

@Injectable({
    providedIn: "root",
})
export class EngineCoreService implements OnDestroy {
    public app: EngineCore | null = null;

    initialize(options?: Partial<IOptionsEngineCore>) {
        this.app = new EngineCore(options);
    }

    ngOnDestroy() {
        this.app = null;
    }
}

// lib/frameworks/svelte/useEngineCore.svelte
<script lang="ts">
    import { onMount, onDestroy } from "svelte"
    import { EngineCore } from "../../index";
    import type { IOptionsEngineCore } from "../../types";

    let app: EngineCore | null = null

    export let options: Partial<IOptionsEngineCore> = {}

    onMount(() => {
        app = new EngineCore(options)
    })

    onDestroy(() => {
        app = null
    })
</script>
