// lib/frameworks/react/useGameCore.ts
import { useEffect, useState } from "react";
import { GameCore } from "../../index";

export const useEngineCore = (load: string) => {
    const [app, setApp] = useState<GameCore | null>(null);

    useEffect(() => {
        const game = new GameCore();

        game.load(load);

        setApp(game);

        return () => {
            setApp(null);
        };
    }, [load]);

    return app;
};

// lib/frameworks/svelte/useGameCore.svelte
<script lang="ts">
    import { onMount, onDestroy } from "svelte"
    import { GameCore } from "../../index";

    let app: GameCore | null = null

    export let load: string = ""

    onMount(async () => {
        app = new GameCore()

        await app.load(load)
    })

    onDestroy(() => {
        app = null
    })
</script>
