// lib/frameworks/angular/useGameCore.ts
import { Injectable, OnDestroy } from "@angular/core";
import { GameCore } from "../../index";

@Injectable({
    providedIn: "root",
})
export class GameCoreService implements OnDestroy {
    public app: GameCore | null = null;

    async initialize(load: string) {
        this.app = new GameCore();

        this.app.load(load);
    }

    ngOnDestroy() {
        this.app = null;
    }
}

// lib/frameworks/svelte/useGameCore.svelte
<script lang="ts">
    import { onMount, onDestroy } from "svelte"
    import { GameCore } from "../../index";

    let app: GameCore | null = null

    export let load: string = ""

    onMount(async () => {
        app = new GameCore()

        await app.load(load)
    })

    onDestroy(() => {
        app = null
    })
</script>
